import fs from "fs";
import seoPrerender from "vite-plugin-seo-prerender";

const chromeExecutablePath = [
    process.env.PUPPETEER_EXECUTABLE_PATH,
    "/Applications/Google Chrome.app/Contents/MacOS/Google Chrome",
    "/Applications/Microsoft Edge.app/Contents/MacOS/Microsoft Edge",
    "/usr/bin/google-chrome",
    "/usr/bin/chromium-browser",
    "/usr/bin/chromium"
].find((filePath) => filePath && fs.existsSync(filePath));

export function seoperender(){
    return seoPrerender({
        routes: [
            '/',
            '/timetran',
            '/md5',
            '/json',
            '/reg',
            '/unicode',
            '/wordcount',
            '/scaletran',
            '/signimage',
            '/randompassword',
            '/urlencode',
            '/ascii',
            '/uuid',
            '/barrage',
            '/unit',
            '/qrcode',
            '/decision',
            '/morse',
            '/random',
            '/numbertochinese',
            '/diff',
            '/markdown',
            '/texttoimg',
            '/webinfo',
            '/bar',
            '/line',
            '/pie',
            '/scatter',
            '/coin',
            '/dice',
            '/textremoveduplicate',
            '/imgcut',
            '/httpstatuscode',
            '/jwt',
            '/htmlentity',
            '/colorpicker',
            '/asciiwordpic',
            '/jsforamt',
            '/htmlformat',
            '/cssformat',
            '/textedit',
            '/base64',
            '/baseconverter',
            '/storageconverter',
            '/hashcalculator',
            '/xmlformat',
            '/sqlformat',
            '/textreplace',
            '/textworkflow',
            '/emoji',
            '/wordfrequency',
            '/wordcloud',
            '/lottery',
            '/rockpaperscissors',
            '/wheel',
            '/imagecolorpicker',
            '/pomodoro',
            '/calculator',
            '/reactiontest',
            '/m3u8player',
            '/imagewatermark',
            '/colorpalette',
            '/about'
        ],
        puppeteer: chromeExecutablePath ? {
            executablePath: chromeExecutablePath
        } : {},
        // network: true,
        // removeStyle: true
    })
}
